import { readFileSync } from 'node:fs';
import { join, relative } from 'node:path';

import fg from 'fast-glob';
import { describe, expect, it } from 'vitest';

// Guard: App Router route modules may export ONLY a closed set of names.
//
// Next type-checks every route.ts against `checkFields<Diff<{...allowed...},
// typeof import('./route.js'), ''>>()`, so ANY extra VALUE export fails
// `next build` with an opaque error:
//
//   Type 'OmitWithTag<typeof import(".../route"), "POST" | "GET" | ... , "">'
//   does not satisfy the constraint '{ [x: string]: never; }'.
//     Property 'X' is incompatible with index signature.
//       Type '"..."' is not assignable to type 'never'.
//
// The trap that makes this worth a test rather than a comment: **`tsc
// --noEmit` does NOT catch it**, because the types doing the checking are
// GENERATED BY THE BUILD ITSELF (.next-stage/types/app/**/route.ts). So the
// full local gate can be green and the build still fails. It has bitten this
// repo twice — api/agents/shift/route.ts (an audit-action constant) and
// api/call-me-now/request-code/route.ts (an OTP purpose tag imported by the
// sibling verify route). This test moves detection from a multi-minute build
// into the test suite, and names the fix in its own failure message.
//
// TYPE-only exports (`export type` / `export interface`) are deliberately
// NOT flagged: `typeof import(...)` sees the value namespace only, so they
// are erased before the check and are genuinely safe.

const repoRoot = join(__dirname, '..', '..');

// Transcribed verbatim from the build-generated checker for the INSTALLED
// Next version (.next-stage/types/app/**/route.ts, read 13.8). If a Next
// upgrade adds a new config export, refresh this list from that file rather
// than from memory or docs — the generated file is the only authority that
// matches what the build will actually enforce.
const ALLOWED_ROUTE_EXPORTS = new Set([
  'GET',
  'HEAD',
  'OPTIONS',
  'POST',
  'PUT',
  'DELETE',
  'PATCH',
  'config',
  'generateStaticParams',
  'instant',
  'prefetch',
  'unstable_dynamicStaleTime',
  'revalidate',
  'dynamic',
  'dynamicParams',
  'fetchCache',
  'preferredRegion',
  'runtime',
  'maxDuration',
]);

/**
 * Value-export names declared in a route module. Covers the forms that
 * actually occur in this repo plus the ones a contributor is most likely to
 * reach for; `export type`/`export interface` are excluded by construction
 * (see header). Deliberately a lexical scan, not a TS-AST parse: the check
 * must stay dependency-light and fast enough to run on every suite.
 */
function valueExportNames(source: string): string[] {
  const names: string[] = [];

  // export const/let/var X ... | export function X | export async function X
  // | export class X | export enum X | export declare const X
  const declRe =
    /^export\s+(?:declare\s+)?(?:const|let|var|(?:async\s+)?function\*?|class|enum)\s+([A-Za-z_$][\w$]*)/gm;
  for (const m of source.matchAll(declRe)) names.push(m[1]);

  // export default ...
  if (/^export\s+default\b/m.test(source)) names.push('default');

  // export { a, b as c } — re-exported values. `export type { ... }` and
  // inline `type` specifiers are skipped, matching the header's rule.
  const braceRe = /^export\s+(?!type\b)\{([^}]*)\}/gm;
  for (const m of source.matchAll(braceRe)) {
    for (const rawSpec of m[1].split(',')) {
      const spec = rawSpec.trim();
      if (!spec || /^type\s/.test(spec)) continue;
      const alias = spec.split(/\s+as\s+/);
      const exported = (alias[1] ?? alias[0]).trim();
      if (exported) names.push(exported);
    }
  }

  return names;
}

describe('App Router route modules export only what Next allows', () => {
  const routeFiles = fg.sync('src/app/**/route.{ts,tsx}', {
    cwd: repoRoot,
    absolute: true,
  });

  it('finds route modules to check (guards against a broken glob)', () => {
    // A silently-empty glob would make this whole suite a no-op that still
    // reports green — the exact failure mode this test exists to prevent.
    expect(routeFiles.length).toBeGreaterThan(0);
  });

  it('no route module has a value export outside the allowed set', () => {
    const offenders: string[] = [];

    for (const file of routeFiles) {
      const source = readFileSync(file, 'utf8');
      for (const name of valueExportNames(source)) {
        if (!ALLOWED_ROUTE_EXPORTS.has(name)) {
          offenders.push(`${relative(repoRoot, file)} → export "${name}"`);
        }
      }
    }

    expect(
      offenders,
      offenders.length === 0
        ? ''
        : `Route modules may only export ${[...ALLOWED_ROUTE_EXPORTS].join(', ')}.\n` +
            `These would fail \`next build\` (and NOT \`tsc --noEmit\`):\n  ` +
            `${offenders.join('\n  ')}\n` +
            `Fix: move the value into a shared module under src/lib/ and import it ` +
            `in the route — never export it from route.ts, and never import one ` +
            `route module from another.`,
    ).toEqual([]);
  });
});
