import { z } from 'zod';

// Validation for the public "call me now" surface (capability A, THIRD
// design, 12.8) — two anonymous, unauthenticated routes:
//   1. POST /api/call-me-now/request-code   — send an SMS OTP to a
//      visitor-named phone number.
//   2. POST /api/call-me-now/verify         — verify the code and, if every
//      admission gate passes, place the call.
//
// Phone SHAPE is deliberately loose here (bounded length only) — the real
// validation is normalizePhone() inside otp.ts's requestOtp/verifyOtp and
// console-calls.ts's evaluateCallMeNowConsent, which is the single source of
// truth for what counts as a valid Israeli E.164 number (src/lib/phone.ts).
// Duplicating a phone regex at the schema layer would only risk drifting
// from that source of truth; this schema's job is bounds/shape only.
const phoneField = z.string().trim().min(1).max(32);

// The OTP purpose tag shared by BOTH routes — request-code issues under it,
// verify consumes under it, and a mismatch would silently reject every valid
// code. It lives HERE, not in either route module, for a hard reason: Next's
// App Router type-checks route modules against a closed set of allowed
// exports, so `export const CALL_ME_NOW_OTP_PURPOSE` inside route.ts fails
// `next build` with "not assignable to type 'never'" — and `tsc --noEmit`
// does NOT catch it, because the offending types are generated by the build
// itself (same trap as api/agents/shift/route.ts's audit-action constant).
// A route importing from another route was the shape that forced the export;
// a shared module removes the need entirely.
export const CALL_ME_NOW_OTP_PURPOSE = 'call_me_now';

// requestOtp generates a zero-padded 6-digit numeric code
// (otp.ts: String(randomInt(0, 1_000_000)).padStart(6, '0')).
const otpCodeField = z.string().trim().regex(/^\d{6}$/, 'code has unexpected shape');

export const callMeNowRequestCodeBodySchema = z.strictObject({
  phone: phoneField,
});
export type CallMeNowRequestCodeBody = z.infer<typeof callMeNowRequestCodeBodySchema>;

export const callMeNowVerifyBodySchema = z.strictObject({
  phone: phoneField,
  code: otpCodeField,
});
export type CallMeNowVerifyBody = z.infer<typeof callMeNowVerifyBodySchema>;
