import { NextResponse } from 'next/server';

import { requireConsoleAgent } from '@/lib/auth/console-agent';
import { agentShiftSchema } from '@/lib/validation/agent-console';
import { rateLimit } from '@/lib/security/rate-limit';
import { createAdminClient } from '@/lib/supabase/admin';

// POST /api/agents/shift   { "active": true|false }   (wake-and-answer, 12.8)
//
// An agent declares their OWN "on shift" intent — a standing, server-
// persisted signal the softphone panel reads to decide whether to
// auto-connect the SDK on launch, and route-inbound reads (via
// notifyOffDutyShiftAgentsOfInboundCall) to decide who gets woken by an
// inbound-call push even while nobody is currently connected. Deliberately
// its OWN table/concept from agent_status (POST /api/agents/status) — see
// console_agent_shift's migration comment and isShiftActiveAndFresh
// (console-calls.ts) for why a reuse of agent_status.status='ready' was
// rejected (a forgotten 'ready' from hours earlier would silently reactivate
// auto-connect on an unrelated page view; console_agent_shift is instead
// read through its own bounded freshness window).
//
// Auth = requireConsoleAgent (Bearer Supabase-JWT + the staff-gated
// is_console_agent), same as /api/agents/status. The write is the agent's
// OWN console_agent_shift row via the caller-scoped client, so RLS
// (console_agent_shift_upsert_own / _update_own) enforces agent_id =
// auth.uid() at the database — the route never trusts a client id. Unlike
// /api/agents/status, this route IS rate-limited (a toggle write is
// infrequent by nature; a tight cap costs a real client nothing) and audited
// (best-effort, non-PII — identifiers only).

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const MAX_BODY_BYTES = 4 * 1024; // a shift body is tiny; reject anything larger
const NO_STORE = { 'Cache-Control': 'no-store' } as const;
const RATE = { limit: 20, windowMs: 60_000 } as const;

// NOT exported: Next's App Router type-checks route modules against a closed
// set of allowed exports (POST/GET/runtime/dynamic/…), and any extra export
// fails `next build` with a "not assignable to type 'never'" error — which
// `tsc --noEmit` does NOT catch, because the offending types are generated by
// the build itself. Nothing outside this file consumes it (grep-verified).
const CONSOLE_SHIFT_AUDIT_ACTION = 'console_call.shift_toggle';

function json(body: unknown, status: number) {
  return NextResponse.json(body, { status, headers: NO_STORE });
}

export async function POST(request: Request) {
  const auth = await requireConsoleAgent(request);
  if (!auth.ok) return json({ error: auth.error }, auth.status);
  const { ctx } = auth;

  const gate = rateLimit(`agent-shift:${ctx.userId}`, RATE);
  if (!gate.allowed) {
    return json({ error: 'יותר מדי בקשות — נסו שוב בעוד רגע' }, 429);
  }

  const raw = await request.text();
  if (raw.length > MAX_BODY_BYTES) return json({ error: 'בקשה גדולה מדי' }, 413);

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return json({ error: 'גוף הבקשה אינו תקין' }, 400);
  }

  const result = agentShiftSchema.safeParse(parsed);
  if (!result.success) return json({ error: 'בקשה לא תקינה' }, 400);

  // Own-row upsert as the caller (RLS-scoped) — same shape as /api/agents/status.
  // console_agent_shift is a real typed table (migration
  // 20260812200243_callcenter_wake_shift_and_flag.sql, pushed and reflected
  // in types.ts — verified live, console audit 12.8); no cast needed.
  const { error } = await ctx.supabase
    .from('console_agent_shift')
    .upsert(
      { agent_id: ctx.userId, active: result.data.active, updated_at: new Date().toISOString() },
      { onConflict: 'agent_id' },
    );
  if (error) return json({ error: 'שמירת המצב נכשלה' }, 500);

  // Best-effort audit, non-PII — service-role direct insert (this route has
  // no cookie session for logActivity(), same reasoning as console-calls.ts's
  // module header).
  try {
    const admin = createAdminClient();
    await admin.from('activity_log').insert({
      event_id: null,
      user_id: ctx.userId,
      action: CONSOLE_SHIFT_AUDIT_ACTION,
      meta: { active: result.data.active },
    });
  } catch {
    // Best-effort — the row write above already succeeded; a lost audit
    // entry never blocks the agent's own toggle.
  }

  return json({ ok: true, active: result.data.active }, 200);
}
