import 'server-only';

import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';

// AES-256-GCM encryption for exchange_connections.credential_* columns (plan
// §4, plans/exchange-ews-stage1.md; schema:
// supabase/migrations/20260727171428_exchange_connections.sql). node:crypto
// only — no third-party crypto dependency.
//
// KEY: EXCHANGE_EWS_ENCRYPTION_KEY, a 32-byte key base64-encoded in env
// (see .env.example). Never NEXT_PUBLIC_, never logged, generated by the
// owner (`openssl rand -base64 32`) and entered directly in the deploy
// environment — this session never creates or sees a real value.
//
// IV: 12 bytes (the GCM-standard nonce size — NOT the 16-byte block size),
// freshly random on every single encryption call. Reusing an IV under the
// same key breaks GCM's confidentiality and authentication guarantees, so
// there is no IV-reuse path here at all — every encryptCredential() call
// draws a new one.
//
// AAD (additional authenticated data): `${connectionId}:${userId}`. This does
// not get encrypted, but it IS authenticated — the auth tag covers ciphertext
// + AAD together. Binding the ciphertext to the specific row and the user who
// owns it means a ciphertext value copied into a different row (or decrypted
// on behalf of a different user) fails the auth-tag check instead of silently
// decrypting into some other credential's plaintext.
//
// FAIL-CLOSED: decryptCredential() has no fallback path. Any mismatch — wrong
// key, wrong key version, tampered ciphertext/iv/tag, wrong AAD — throws.
// Callers (src/lib/data/exchange-connections.ts) must not swallow that into a
// default value; a decrypt failure means the credential is unusable and the
// connection must surface as failed, never silently skipped.
const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH_BYTES = 12;
const AUTH_TAG_LENGTH_BYTES = 16;
const KEY_LENGTH_BYTES = 32;

// No rotation mechanism exists yet — only version 1 is supported. Rotation
// (plan §4: "encryption_key_version + ..._KEY_PREVIOUS בזמן מעבר") is
// explicitly out of Stage-1 scope; the owner's task list adds only
// EXCHANGE_EWS_ENCRYPTION_KEY to .env.example, not a "_PREVIOUS" variant.
// A row with any other key_version fails closed rather than guessing.
export const CURRENT_ENCRYPTION_KEY_VERSION = 1;

export type EncryptedCredential = {
  ciphertext: string; // base64
  iv: string; // base64, 12 bytes decoded
  authTag: string; // base64, 16 bytes decoded
  keyVersion: number;
};

function resolveKey(keyVersion: number): Buffer {
  if (keyVersion !== CURRENT_ENCRYPTION_KEY_VERSION) {
    throw new Error('Unsupported Exchange credential encryption key version');
  }
  const raw = process.env.EXCHANGE_EWS_ENCRYPTION_KEY;
  if (!raw) {
    throw new Error('EXCHANGE_EWS_ENCRYPTION_KEY is not configured');
  }
  const key = Buffer.from(raw, 'base64');
  if (key.length !== KEY_LENGTH_BYTES) {
    throw new Error('EXCHANGE_EWS_ENCRYPTION_KEY must decode to exactly 32 bytes');
  }
  return key;
}

function buildAad(connectionId: string, userId: string): Buffer {
  return Buffer.from(`${connectionId}:${userId}`, 'utf8');
}

export function encryptCredential(
  plaintext: string,
  connectionId: string,
  userId: string,
): EncryptedCredential {
  const keyVersion = CURRENT_ENCRYPTION_KEY_VERSION;
  const key = resolveKey(keyVersion);
  const iv = randomBytes(IV_LENGTH_BYTES);
  const cipher = createCipheriv(ALGORITHM, key, iv, {
    authTagLength: AUTH_TAG_LENGTH_BYTES,
  });
  cipher.setAAD(buildAad(connectionId, userId));
  const ciphertext = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return {
    ciphertext: ciphertext.toString('base64'),
    iv: iv.toString('base64'),
    authTag: authTag.toString('base64'),
    keyVersion,
  };
}

export function decryptCredential(
  encrypted: EncryptedCredential,
  connectionId: string,
  userId: string,
): string {
  const key = resolveKey(encrypted.keyVersion);
  const iv = Buffer.from(encrypted.iv, 'base64');
  if (iv.length !== IV_LENGTH_BYTES) {
    throw new Error('Invalid Exchange credential IV length');
  }
  const authTag = Buffer.from(encrypted.authTag, 'base64');
  if (authTag.length !== AUTH_TAG_LENGTH_BYTES) {
    throw new Error('Invalid Exchange credential auth tag length');
  }
  const decipher = createDecipheriv(ALGORITHM, key, iv, {
    authTagLength: AUTH_TAG_LENGTH_BYTES,
  });
  decipher.setAuthTag(authTag);
  decipher.setAAD(buildAad(connectionId, userId));
  // decipher.final() throws (e.g. "Unsupported state or unable to
  // authenticate data") if the auth tag does not verify — that IS the
  // fail-closed check; there is no separate "is it valid" step to skip.
  const plaintext = Buffer.concat([
    decipher.update(Buffer.from(encrypted.ciphertext, 'base64')),
    decipher.final(),
  ]);
  return plaintext.toString('utf8');
}
