/**
 * Relocation wizard — nginx vhost rendering and operations.
 *
 * Templates are derived from the PROVEN production vhost
 * (/etc/nginx/conf.d/beta-proxy.conf) and keep its two load-bearing blocks
 * verbatim in spirit:
 * - the enlarged proxy buffers (32k / 16x16k / 64k) — without them the
 *   Supabase chunked auth cookies overflow nginx's default header buffer and
 *   /admin 502s return (the fixed 2026-07 incident);
 * - the ACME location (/.well-known/acme-challenge/ → the Plesk default
 *   docroot) — cert issuance AND renewals break without it.
 *
 * The redirect vhost 301s everything EXCEPT /api/*, which keeps proxying to
 * the app: Voximplant platform callbacks and the installed Android builds
 * POST there, and POST bodies do not survive a 301 (plan Stage E).
 *
 * All rendered config is ASCII-only — nginx files are no place for RTL text.
 */
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  assertExecuteLatch,
  backupStamp,
  runCommand,
  type RunCommandResult,
} from "./exec";

export const PLESK_LE_LIVE_DIR = "/opt/psa/var/modules/letsencrypt/etc/live";
export const ACME_WEBROOT = "/var/www/vhosts/default/htdocs";
export const APP_UPSTREAM = "127.0.0.1:3002";

/** Stable renewal-safe cert paths for a domain issued via the Plesk Let's
 * Encrypt extension. */
export function pleskCertPaths(domain: string): { certPath: string; keyPath: string } {
  return {
    certPath: `${PLESK_LE_LIVE_DIR}/${domain}/fullchain.pem`,
    keyPath: `${PLESK_LE_LIVE_DIR}/${domain}/privkey.pem`,
  };
}

/** nginx variable names cannot carry dots/dashes — derive a per-domain slug so
 * two rendered vhosts never collide on the upgrade-map variable. */
function mapSlug(domain: string): string {
  return domain.replace(/[^a-zA-Z0-9]/g, "_");
}

/** `listen` directive value: Plesk's own vhosts listen on an explicit
 * IP:port, and nginx prefers the most specific listen match — a wildcard
 * `*:443` block LOSES to Plesk's `IP:443` block for the same server_name, so
 * shadowing only works when we bind the same explicit address. The address is
 * a parameter (resolved at runtime by preflight — never hardcoded, R1). */
function listenValue(port: number, listenAddress?: string): string {
  return listenAddress ? `${listenAddress}:${port}` : String(port);
}

export interface AppVhostParams {
  domain: string;
  certPath: string;
  keyPath: string;
  /** Explicit bind address (the server's public IP). Empty = bare port. */
  listenAddress?: string;
}

const PROXY_BLOCK = `        proxy_pass http://${APP_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $CONN_VAR;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;

        # Authenticated /admin routes emit large Set-Cookie headers (Supabase
        # chunked auth-token cookies) whose combined size overflows nginx's
        # default ~8k proxy header buffer -> "upstream sent too big header"
        # 502s. The full upstream response header block must fit in a single
        # proxy_buffer_size buffer, so enlarge it. (Fixed incident, 2026-07.)
        proxy_buffer_size       32k;
        proxy_buffers           16 16k;
        proxy_busy_buffers_size 64k;`;

const ACME_LOCATION = `    location ^~ /.well-known/acme-challenge/ {
        root ${ACME_WEBROOT};
        default_type text/plain;
    }`;

/** Full serving vhost for the app on `domain` — the beta-proxy.conf shape,
 * parameterized. */
export function renderAppVhost(params: AppVhostParams): string {
  const conn = `${mapSlug(params.domain)}_connection_upgrade`;
  const proxy = PROXY_BLOCK.replace(/\$CONN_VAR/g, `$${conn}`);
  return `# ${params.domain} — KALFA Event Magic (Next.js, next start) reverse proxy
# Generated by the relocation wizard. Loaded from conf.d before
# zz010_psa_nginx.conf, so this shadows any Plesk vhost for the same name.

map $http_upgrade $${conn} {
    default upgrade;
    ''      close;
}

server {
    listen ${listenValue(443, params.listenAddress)} ssl;
    http2 on;
    server_name ${params.domain};

    ssl_certificate     ${params.certPath};
    ssl_certificate_key ${params.keyPath};

    client_max_body_size 25M;

${ACME_LOCATION}

    location / {
${proxy}
    }
}

server {
    listen ${listenValue(80, params.listenAddress)};
    server_name ${params.domain};

${ACME_LOCATION}
    location / {
        return 301 https://$host$request_uri;
    }
}
`;
}

export interface RedirectVhostParams {
  fromDomain: string;
  /** Bare https origin the old domain now points at. */
  toOrigin: string;
  certPath?: string;
  keyPath?: string;
  listenAddress?: string;
}

/** Old-origin continuity vhost (plan Stage E): 301 everything to the new
 * origin EXCEPT /api/*, which keeps proxying to the app until the Voximplant
 * callback re-registration is verified and the installed Android fleet has
 * moved (their POSTs are hardcoded to the old origin and do not survive 301). */
export function renderRedirectVhost(params: RedirectVhostParams): string {
  const certs = {
    certPath: params.certPath ?? pleskCertPaths(params.fromDomain).certPath,
    keyPath: params.keyPath ?? pleskCertPaths(params.fromDomain).keyPath,
  };
  const conn = `${mapSlug(params.fromDomain)}_connection_upgrade`;
  const proxy = PROXY_BLOCK.replace(/\$CONN_VAR/g, `$${conn}`);
  return `# ${params.fromDomain} — old-origin continuity after relocation to ${params.toOrigin}
# Generated by the relocation wizard (plan Stage E). Everything 301s to the
# new origin; /api/* keeps proxying (POST callers - Voximplant callbacks,
# installed Android builds - do not survive a 301).

map $http_upgrade $${conn} {
    default upgrade;
    ''      close;
}

server {
    listen ${listenValue(443, params.listenAddress)} ssl;
    http2 on;
    server_name ${params.fromDomain};

    ssl_certificate     ${certs.certPath};
    ssl_certificate_key ${certs.keyPath};

    client_max_body_size 25M;

${ACME_LOCATION}

    location /api/ {
${proxy}
    }

    location / {
        return 301 ${params.toOrigin}$request_uri;
    }
}

server {
    listen ${listenValue(80, params.listenAddress)};
    server_name ${params.fromDomain};

${ACME_LOCATION}
    location /api/ {
        return 301 https://$host$request_uri;
    }
    location / {
        return 301 ${params.toOrigin}$request_uri;
    }
}
`;
}

/** Write a vhost file into root-owned territory: back up any existing target
 * (sudo cp, timestamped), stage the content in a private temp dir we own,
 * `sudo cp` it into place, clean the temp. cp is not rename-atomic, but nginx
 * only re-reads config on reload — the wizard always tests + reloads after. */
export async function writeVhost(
  path: string,
  content: string,
): Promise<{ path: string; backupPath: string | null }> {
  assertExecuteLatch(`writeVhost(${path})`);
  let backupPath: string | null = null;
  const probe = await runCommand({ cmd: "test", args: ["-e", path], sudo: true });
  if (probe.ok) {
    backupPath = `${path}.bak-${backupStamp()}`;
    const cp = await runCommand({ cmd: "cp", args: [path, backupPath], sudo: true });
    if (!cp.ok) throw new Error(`backing up ${path} failed: ${cp.command}`);
  }
  const dir = mkdtempSync(join(tmpdir(), "relocate-vhost-"));
  const staged = join(dir, "vhost.conf");
  try {
    writeFileSync(staged, content, { mode: 0o644 });
    const cp = await runCommand({ cmd: "cp", args: [staged, path], sudo: true });
    if (!cp.ok) throw new Error(`writing ${path} failed: ${cp.command}`);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
  return { path, backupPath };
}

/** `nginx -t` (read-only). Exit 0 = pass — nginx warns-but-passes on the
 * benign duplicate-server_name shadowing this setup relies on, so warnings
 * are returned for display, never treated as failure. */
export async function nginxTest(): Promise<{ ok: boolean; output: string }> {
  const res = await runCommand({ cmd: "nginx", args: ["-t"], sudo: true });
  return { ok: res.ok, output: `${res.stdout}${res.stderr}`.trim() };
}

/** Graceful reload — zero-downtime config swap. */
export async function nginxReload(): Promise<RunCommandResult> {
  assertExecuteLatch("nginxReload");
  return runCommand({ cmd: "systemctl", args: ["reload", "nginx"], sudo: true });
}
