import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

// fill_authorized_set cannot be run without a test database, so the properties that make it safe are pinned on the
// migration SQL. Each assertion below is a rule from the plan, not a style preference.

const DIR = join(__dirname, '../../../supabase/migrations');
const read = (suffix: string) => {
  const file = readdirSync(DIR).find((f) => f.endsWith(suffix));
  expect(file, suffix).toBeDefined();
  return readFileSync(join(DIR, file as string), 'utf8');
};
// Comments are documentation: the rules are checked against the executable statements only.
const code = (sql: string) => sql.replace(/--.*$/gm, '');

describe('20261005..._fill_authorized_set.sql', () => {
  const sql = read('_fill_authorized_set.sql');
  const body = code(sql);

  it('only TOPS UP: it never removes a member of the list', () => {
    expect(body).not.toMatch(/\bdelete\s+from\b/i);
    expect(body).not.toMatch(/\btruncate\b/i);
  });

  it('locks the campaign row first, so it is serialised with reconcile_authorized_set', () => {
    expect(body).toMatch(/from\s+public\.campaigns\s+where\s+id\s*=\s*p_campaign\s+for update/i);
  });

  it('refuses the wrong event, a non-operational campaign and a campaign without a quota — before it writes anything', () => {
    const firstInsert = body.search(/insert\s+into/i);
    for (const verdict of ['no_campaign', 'event_mismatch', 'not_operational', 'no_quota']) {
      const at = body.indexOf(`'${verdict}'`);
      expect(at, verdict).toBeGreaterThan(-1);
      expect(at, verdict).toBeLessThan(firstInsert);
    }
  });

  it('admits only what reconcile_authorized_set admits: this event, not opted out, with a live guest', () => {
    expect(body).toMatch(/c\.event_id\s*=\s*v_event_id/);
    expect(body).toMatch(/c\.removal_requested\s*=\s*false/);
    expect(body).toMatch(/fg\.first_seq is not null/i);
  });

  it('ranks by the smallest guests.seq of the contact, and takes only the room that is left', () => {
    expect(body).toMatch(/min\(g\.seq\)/i);
    expect(body).toMatch(/order by fg\.first_seq, c\.id/i);
    expect(body).toMatch(/v_room\s*:=\s*greatest\(v_quota - v_size, 0\)/i);
    expect(body).toMatch(/limit v_room/i);
  });

  it('records every admission with the audit vocabulary the table allows (action in, reason snapshot)', () => {
    expect(body).toMatch(/'in',\s*'snapshot'/);
  });

  it('is SECURITY DEFINER with a fixed search_path and callable by the service role only', () => {
    expect(body).toMatch(/security definer/i);
    expect(body).toMatch(/set search_path to 'public'/i);
    expect(body).toMatch(/revoke all on function public\.fill_authorized_set\(uuid, uuid, text\) from public, anon, authenticated/i);
    expect(body).toMatch(/grant execute on function public\.fill_authorized_set\(uuid, uuid, text\) to service_role/i);
    // every GRANT of the function goes to the service role and nobody else
    const grantees = [...body.matchAll(/grant execute on function [^;]*? to (\w+)/gi)].map((m) => m[1]);
    expect(grantees).toEqual(['service_role']);
  });

  it('documents its rollback and what it depends on', () => {
    expect(sql).toContain('ROLLBACK');
    expect(sql).toContain('20261005041849_guests_seq_order.sql');
  });
});

describe('20261005..._guests_seq_order.sql', () => {
  const sql = read('_guests_seq_order.sql');
  const body = code(sql);

  it('adds an identity column assigned by the database, not by the application', () => {
    expect(body).toMatch(/add column seq bigint generated by default as identity/i);
  });

  it('numbers the existing guests once, by (created_at, id), without moving updated_at', () => {
    expect(body).toMatch(/row_number\(\) over \(order by created_at, id\)/i);
    expect(body).toMatch(/disable trigger trg_guests_updated/i);
    expect(body).toMatch(/enable trigger trg_guests_updated/i);
    expect(body.indexOf('disable trigger')).toBeLessThan(body.indexOf('update public.guests'));
    expect(body.indexOf('update public.guests')).toBeLessThan(body.indexOf('enable trigger'));
  });

  it('continues new rows after the backfill and makes seq unique and indexable per event', () => {
    expect(body).toMatch(/setval\(pg_get_serial_sequence\('public\.guests', 'seq'\)/i);
    expect(body).toMatch(/create unique index guests_seq_uq on public\.guests \(seq\)/i);
    expect(body).toMatch(/create index guests_event_seq_idx on public\.guests \(event_id, seq\)/i);
  });

  it('documents its rollback', () => {
    expect(sql).toContain('ROLLBACK');
  });
});
