-- ref_code: short random per-inquiry reference embedded as [KLF-XXXXXXXX] in every
-- outbound subject on a thread (templates.ts threadSubject()), matched first by
-- intakeMailAsInquiry (inquiry-mail-intake.ts findExistingInquiry) before falling back
-- to conversationId — always paired with a sender-email identity check on EITHER tier,
-- never trusted alone (see docs/inquiry-email-threading-fix-plan-2026-08-25.md §2.1/§2.3
-- for the entropy tradeoff and matching design).
--
-- DEFAULT-generated (not app-layer): the two existing INSERT paths into
-- contact_messages -- insertContactMessage (inquiry-intake.ts) and the upsert in
-- intakeMailAsInquiry (inquiry-mail-intake.ts), confirmed exhaustive by the write-path
-- audit in 20260825133136_contact_messages_status_check.sql -- need no code change:
-- Postgres fills ref_code on every insert automatically.
--
-- Verified live before applying (same verify-first step as the CHECK constraint):
--   * search_path on this project is "$user", public, extensions (checked 2026-08-25
--     via `show search_path;`) -- extensions is on the path, so the bare
--     gen_random_bytes(...) form below resolves correctly, matching the precedent in
--     20260705120408_event_gift_and_invite_media.sql (no extensions.-prefix needed,
--     unlike 202606290034_rsvp_harden.sql).
--   * Row count / no existing ref_code values to collide with, before backfill.
--
-- Rollback:
--   alter table public.contact_messages
--     drop constraint if exists contact_messages_ref_code_key,
--     drop column if exists ref_code;
--
-- NOTE (independent audit 2026-08-25, PRODUCT DECISION -- not resolved here, see §4.1):
-- unlike ref_code's uniqueness (enforced below), its FORMAT is only ever produced by the
-- DEFAULT expression -- there is no CHECK constraint stopping a future explicit insert
-- from writing a value that doesn't match /^[0-9A-F]{8}$/, which would then silently
-- never match REF_CODE_RE on intake. Whether to add
-- `check (ref_code ~ '^[0-9A-F]{8}$')` (precedent: contact_messages_status_valid on
-- this same table) is an open decision requiring owner sign-off -- see §4.1.

alter table public.contact_messages
  add column if not exists ref_code text
    default upper(encode(gen_random_bytes(4), 'hex'));

-- Backfill existing rows before the NOT NULL + UNIQUE land — verify count/collisions
-- against live data first, same process as contact_messages_status_check.
update public.contact_messages
  set ref_code = upper(encode(gen_random_bytes(4), 'hex'))
  where ref_code is null;

alter table public.contact_messages
  alter column ref_code set not null;

-- Guarded for idempotency (ALTER TABLE ... ADD CONSTRAINT has no IF NOT EXISTS, and a
-- re-run after a `db push` that already applied but reported a false failure -- see
-- memory: parallel-sessions-one-live-db -- must not abort on 42710). Same pattern as
-- contact_messages_status_valid / contact_messages_rating_token_key, both added to this
-- same table today.
--
-- FIXED (independent audit 2026-08-25, CONFIRMED, table row 11): pg_constraint's own
-- documentation states conname is "not necessarily unique" globally -- confirmed
-- empirically on this project's live DB, where duplicate constraint names already exist
-- across schemas (e.g. messages_payload_exclusive appears 8 times, schema_migrations_pkey
-- 3 times), though not yet for this specific name. The earlier draft's `where conname =
-- ...` alone could, in principle, match a same-named constraint on an unrelated table and
-- skip adding this one. Scoped to this table explicitly below.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'contact_messages_ref_code_key'
      and conrelid = 'public.contact_messages'::regclass
  ) then
    alter table public.contact_messages
      add constraint contact_messages_ref_code_key unique (ref_code);
  end if;
end $$;

comment on column public.contact_messages.ref_code is
  'Random reference code (upper(encode(gen_random_bytes(4), ''hex'')), 8 hex chars / 32 bits -- intentionally weaker than rating_token''s 128 bits because it is never trusted alone, see AND-check in findExistingInquiry) embedded as [KLF-XXXXXXXX] in every outbound subject on this inquiry''s thread (admin reply, reminder, closing warning, rating request -- src/lib/email/templates.ts threadSubject()). DB-generated by DEFAULT on every insert, no application insert-path change needed. Unique so intakeMailAsInquiry can match an inbound reply by subject token as its first-tier check, before falling back to conversationId -- always paired with a sender-email identity check on either tier.';

-- `SET NOT NULL` is left unguarded deliberately — re-running it on an already-not-null
-- column is a no-op in Postgres, unlike `ADD CONSTRAINT`, which has no native
-- `IF NOT EXISTS` and must be wrapped.
