-- Stable "order of addition" for guests (contact-quota package: the first N added are inside).
-- Plan: docs/superpowers/plans/2026-10-04-package-payment-plan.md Task 1.
--
-- WHY NOT created_at: a bulk import inserts every row in one statement, so all rows share now().
-- Measured 2026-10-04: 39 of the 43 guests of the largest event have the same created_at.
--
-- seq is an IDENTITY column: the default is evaluated per row, in the order the rows are produced by the
-- INSERT (a PostgREST bulk insert is one statement over the JSON array, so that is the file order), and an
-- identity default needs no separate USAGE grant on the sequence for authenticated writers.
--
-- Existing rows: the file order of past imports is not recoverable (their rows share created_at), so they are
-- numbered by (created_at, id) — fixed and repeatable. Only the live test events are affected.
-- trg_guests_updated is disabled for the backfill so updated_at of existing guests does not move.
-- Measured live 2026-10-05 (read-only), before writing this file: trg_guests_updated is the ONLY non-internal
-- trigger on public.guests, the table is in no publication (no realtime fan-out) and holds 45 rows.
--
-- ROLLBACK: drop index guests_event_seq_idx; drop index guests_seq_uq; alter table public.guests drop column seq;

alter table public.guests add column seq bigint generated by default as identity;

alter table public.guests disable trigger trg_guests_updated;
with ordered as (
  select id, row_number() over (order by created_at, id) as rn from public.guests
)
update public.guests g set seq = o.rn from ordered o where g.id = o.id;
alter table public.guests enable trigger trg_guests_updated;

-- New rows continue after the backfill.
select setval(pg_get_serial_sequence('public.guests', 'seq'),
              coalesce((select max(seq) from public.guests), 0) + 1, false);

create unique index guests_seq_uq on public.guests (seq);
create index guests_event_seq_idx on public.guests (event_id, seq);

comment on column public.guests.seq is
  'Order of addition. Monotonic, unique, assigned by the database. A contact''s rank in the contact-quota model is the minimum seq among its guests. Do not use created_at for ordering: bulk inserts share it.';
